# golangci-lint configuration for C8S
# See https://golangci-lint.run/usage/configuration/

run:
  timeout: 10m
  go: '1.25'
  modules-download-mode: readonly

linters:
  enable:
    - gofmt          # Check code is formatted
    - goimports      # Check imports are formatted
    - govet          # Go vet examines Go source code
    - errcheck       # Check for unchecked errors
    - staticcheck    # Staticcheck is a go vet on steroids
    - unused         # Check for unused constants, variables, functions
    - gosimple       # Simplify code
    - ineffassign    # Detect ineffectual assignments
    - typecheck      # Type check errors
    - gocritic       # Comprehensive Go linter
    - misspell       # Spelling mistakes
    - revive         # Fast, configurable, extensible, flexible linter
    - bodyclose      # Check HTTP response bodies are closed
    - nilerr         # Find code returning nil with non-nil error
    - nolintlint     # Ill-formed or insufficient nolint directives
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Reports unused function parameters
    - exportloopref  # Checks for pointers to enclosing loop variables
    - goconst        # Find repeated strings that could be constants
    - godot          # Check comments end in period
    - gocyclo        # Cyclomatic complexity
    - nestif         # Report deeply nested if statements

linters-settings:
  gocyclo:
    min-complexity: 15

  gocritic:
    enabled-tags:
      - diagnostic
      - performance
      - style
    disabled-checks:
      - ifElseChain
      - hugeParam

  revive:
    rules:
      - name: blank-imports
      - name: context-as-argument
      - name: context-keys-type
      - name: error-return
      - name: error-strings
      - name: error-naming
      - name: exported
      - name: increment-decrement
      - name: var-naming
      - name: package-comments
      - name: range
      - name: receiver-naming
      - name: indent-error-flow
      - name: superfluous-else
      - name: unreachable-code

  godot:
    scope: declarations
    capital: true

  misspell:
    locale: US

  nestif:
    min-complexity: 5

issues:
  # Maximum issues count per one linter
  max-issues-per-linter: 0

  # Maximum count of issues with the same text
  max-same-issues: 0

  # Exclude some linters from running on tests
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - goconst
        - unparam

    # Exclude known issues in generated code
    - path: zz_generated\.deepcopy\.go
      linters:
        - gocritic
        - gocyclo
        - revive

    # Exclude shadow checking on err variables (very common in Go)
    - text: "shadow: declaration of \"err\""
      linters:
        - govet

    # Exclude some staticcheck checks on tests
    - path: _test\.go
      text: "SA1019:"  # Deprecated functions in tests are ok
      linters:
        - staticcheck

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true
  sort-results: true
