/**
 * Screenshot specifications for documentation
 * Defines all screenshots to capture and their configurations
 */

export interface ScreenshotSpec {
  /** Feature/category name */
  feature: string;
  /** Human-readable screen name */
  screenName: string;
  /** Setup function to navigate to this screen */
  setup: () => Promise<void>;
  /** Optional: CSS selector for element-specific screenshot */
  element?: string;
  /** Optional: Custom filename (without .png) */
  filename?: string;
  /** Optional: Wait for specific selectors before capturing */
  readinessSelectors?: string[];
  /** Optional: Whether to capture responsive variants */
  responsive?: boolean;
  /** Optional: Description for documentation */
  description?: string;
  /** Optional: Wait time in ms before screenshot */
  waitTime?: number;
  /** Optional: Full page screenshot */
  fullPage?: boolean;
}

/**
 * Define all screenshots to capture for documentation
 * These will be generated by the screenshot collection script
 */
export const SCREENSHOTS: ScreenshotSpec[] = [
  // Authentication Screens
  {
    feature: 'authentication',
    screenName: 'login-page',
    filename: 'login-page',
    description: 'Login page with email and password fields',
    setup: async () => {
      // Will be set up in the test
    },
    responsive: true,
  },

  // Dashboard Screens
  {
    feature: 'dashboard',
    screenName: 'pipeline-list-empty',
    filename: 'pipeline-list-empty',
    description: 'Empty dashboard when no pipelines exist',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'dashboard',
    screenName: 'pipeline-list-with-runs',
    filename: 'pipeline-list-with-runs',
    description: 'Dashboard with pipeline runs and status',
    setup: async () => {
      // Setup handled in test
    },
    readinessSelectors: ['[data-testid="pipeline-list"]'],
  },
  {
    feature: 'dashboard',
    screenName: 'quick-stats-panel',
    filename: 'quick-stats-panel',
    description: 'Quick statistics panel showing metrics',
    setup: async () => {
      // Setup handled in test
    },
    element: '[data-testid="quick-stats"]',
  },
  {
    feature: 'dashboard',
    screenName: 'filter-panel',
    filename: 'filter-panel',
    description: 'Advanced filter panel for pipeline runs',
    setup: async () => {
      // Setup handled in test
    },
    element: '[data-testid="filter-panel"]',
  },

  // Pipeline Detail Screens
  {
    feature: 'pipeline',
    screenName: 'pipeline-detail',
    filename: 'pipeline-detail',
    description: 'Individual pipeline run details',
    setup: async () => {
      // Setup handled in test
    },
    readinessSelectors: ['[data-testid="pipeline-detail"]'],
  },
  {
    feature: 'pipeline',
    screenName: 'pipeline-running',
    filename: 'pipeline-running',
    description: 'Pipeline in running state with progress',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'pipeline',
    screenName: 'pipeline-completed',
    filename: 'pipeline-completed',
    description: 'Completed pipeline with summary',
    setup: async () => {
      // Setup handled in test
    },
  },

  // Log Viewing Screens
  {
    feature: 'logs',
    screenName: 'log-viewer',
    filename: 'log-viewer',
    description: 'Real-time log viewer with search',
    setup: async () => {
      // Setup handled in test
    },
    readinessSelectors: ['[data-testid="log-viewer"]'],
  },
  {
    feature: 'logs',
    screenName: 'log-search',
    filename: 'log-search',
    description: 'Log viewer with search highlighting',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'logs',
    screenName: 'log-filters',
    filename: 'log-filters',
    description: 'Log filtering by level and timestamp',
    setup: async () => {
      // Setup handled in test
    },
  },

  // Artifact Management Screens
  {
    feature: 'artifacts',
    screenName: 'artifact-list',
    filename: 'artifact-list',
    description: 'Artifact browser and file list',
    setup: async () => {
      // Setup handled in test
    },
    readinessSelectors: ['[data-testid="artifact-list"]'],
  },
  {
    feature: 'artifacts',
    screenName: 'artifact-preview',
    filename: 'artifact-preview',
    description: 'Artifact preview (image/text)',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'artifacts',
    screenName: 'artifact-download',
    filename: 'artifact-download',
    description: 'Artifact download options',
    setup: async () => {
      // Setup handled in test
    },
  },

  // Project Management Screens
  {
    feature: 'projects',
    screenName: 'project-list',
    filename: 'project-list',
    description: 'List of all projects',
    setup: async () => {
      // Setup handled in test
    },
    readinessSelectors: ['[data-testid="project-list"]'],
  },
  {
    feature: 'projects',
    screenName: 'project-detail',
    filename: 'project-detail',
    description: 'Individual project settings and webhooks',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'projects',
    screenName: 'webhook-config',
    filename: 'webhook-config',
    description: 'Webhook configuration interface',
    setup: async () => {
      // Setup handled in test
    },
  },

  // UI Components Screens
  {
    feature: 'components',
    screenName: 'status-badges',
    filename: 'status-badges',
    description: 'Status badges (success, failed, running)',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'components',
    screenName: 'error-messages',
    filename: 'error-messages',
    description: 'Error and validation messages',
    setup: async () => {
      // Setup handled in test
    },
  },
  {
    feature: 'components',
    screenName: 'loading-states',
    filename: 'loading-states',
    description: 'Loading skeletons and spinners',
    setup: async () => {
      // Setup handled in test
    },
  },

  // Keyboard Shortcuts Screens
  {
    feature: 'keyboard-shortcuts',
    screenName: 'help-modal',
    filename: 'help-modal',
    description: 'Keyboard shortcuts help modal',
    setup: async () => {
      // Setup handled in test
    },
  },

  // Responsive Design Examples
  {
    feature: 'responsive',
    screenName: 'mobile-dashboard',
    filename: 'mobile-dashboard',
    description: 'Dashboard on mobile device',
    setup: async () => {
      // Setup handled in test
    },
    responsive: true,
  },
  {
    feature: 'responsive',
    screenName: 'tablet-pipeline-detail',
    filename: 'tablet-pipeline-detail',
    description: 'Pipeline detail on tablet',
    setup: async () => {
      // Setup handled in test
    },
    responsive: true,
  },
];

/**
 * Feature groupings for documentation organization
 * Maps feature names to their documentation sections
 */
export const FEATURE_DOCS: Record<string, string> = {
  authentication: 'docs/guides/dashboard-features.md',
  dashboard: 'docs/guides/dashboard-features.md',
  pipeline: 'docs/guides/dashboard-features.md',
  logs: 'docs/guides/dashboard-features.md',
  artifacts: 'docs/guides/dashboard-features.md',
  projects: 'docs/guides/dashboard-features.md',
  components: 'docs/guides/dashboard-features.md',
  'keyboard-shortcuts': 'docs/guides/dashboard-features.md',
  responsive: 'docs/guides/dashboard-features.md',
};

/**
 * Get screenshot specs for a specific feature
 */
export function getFeatureScreenshots(feature: string): ScreenshotSpec[] {
  return SCREENSHOTS.filter(spec => spec.feature === feature);
}

/**
 * Get all unique features
 */
export function getAllFeatures(): string[] {
  return Array.from(new Set(SCREENSHOTS.map(spec => spec.feature)));
}

/**
 * Get responsive screenshot specs
 */
export function getResponsiveScreenshots(): ScreenshotSpec[] {
  return SCREENSHOTS.filter(spec => spec.responsive === true);
}
