---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: controller-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c8s.dev
  resources:
  - pipelineconfigs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - c8s.dev
  resources:
  - pipelineruns
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - c8s.dev
  resources:
  - pipelineruns/finalizers
  verbs:
  - update
- apiGroups:
  - c8s.dev
  resources:
  - pipelineruns/status
  verbs:
  - get
  - patch
  - update
