{{- if .Values.components.webhook.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "c8s.fullname" . }}-webhook-config
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
data:
  WEBHOOK_PORT: {{ .Values.components.webhook.port.containerPort | quote }}
  LOG_LEVEL: {{ .Values.environment.logLevel | quote }}
{{- end }}
