{{- if .Values.components.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c8s.fullname" . }}-webhook
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.components.webhook.port.servicePort }}
    targetPort: https
    protocol: TCP
    name: https
  selector:
    {{- include "c8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: webhook
{{- end }}
