apiVersion: v1
kind: Service
metadata:
  name: c8s-webhook
  namespace: c8s-system
  labels:
    app: c8s-webhook
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  selector:
    app: c8s-webhook
  sessionAffinity: None
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: c8s-webhook
  namespace: c8s-system
  labels:
    app: c8s-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: c8s-webhook
  labels:
    app: c8s-webhook
rules:
- apiGroups:
  - c8s.io
  resources:
  - pipelineruns
  - pipelineconfigs
  - repositoryconnections
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: c8s-webhook
  labels:
    app: c8s-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: c8s-webhook
subjects:
- kind: ServiceAccount
  name: c8s-webhook
  namespace: c8s-system
