{{- if .Values.components.controller.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "c8s.fullname" . }}-controller
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.components.controller.port.servicePort }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "c8s.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
