{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "c8s.serviceAccountName" . }}
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
{{- end }}
