{{- if and (eq .Values.storage.type "pvc") .Values.storage.pvc.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "c8s.fullname" . }}-pvc
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
spec:
  accessModes:
  - {{ .Values.storage.pvc.accessMode }}
  {{- if .Values.storage.pvc.storageClass }}
  storageClassName: {{ .Values.storage.pvc.storageClass }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.pvc.size }}
{{- end }}
