{{- if and (eq .Values.storage.type "s3-compatible") .Values.storage.s3.enabled }}
{{- if or .Values.storage.s3.accessKey .Values.storage.s3.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c8s.fullname" . }}-s3-credentials
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{- include "c8s.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.s3.accessKey }}
  S3_ACCESS_KEY: {{ .Values.storage.s3.accessKey | b64enc }}
  {{- end }}
  {{- if .Values.storage.s3.secretKey }}
  S3_SECRET_KEY: {{ .Values.storage.s3.secretKey | b64enc }}
  {{- end }}
{{- end }}
{{- end }}
