{{- if eq .Values.storage.type "s3-compatible" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "c8s.fullname" . }}-s3-secret
  namespace: {{ include "c8s.namespace" . }}
  labels:
    {{ include "c8s.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.storage.s3.accessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.storage.s3.accessKey | b64enc }}
  {{- end }}
  {{- if .Values.storage.s3.secretKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.storage.s3.secretKey | b64enc }}
  {{- end }}
{{- end }}
