name: CI

on:
  push:
    branches: [ main, 'release-*' ]
  pull_request:
    branches: [ main, 'release-*' ]

env:
  GO_VERSION: '1.25'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
          args: --timeout=10m

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Run unit tests
        run: make test-unit

      - name: Setup envtest
        run: go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest

      - name: Run integration tests
        run: make test-integration

      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.out
          flags: unittests
          name: codecov-c8s

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Download dependencies
        run: go mod download

      - name: Build all binaries
        run: make build

      - name: Verify manifests
        run: |
          make manifests
          git diff --exit-code config/crd/bases

  docker:
    name: Docker Build
    runs-on: ubuntu-latest
    needs: [lint, test, build]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build controller image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: controller
          push: false
          tags: c8s-controller:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build API server image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: api-server
          push: false
          tags: c8s-api-server:test
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build webhook image
        uses: docker/build-push-action@v5
        with:
          context: .
          target: webhook
          push: false
          tags: c8s-webhook:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
